# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/Into Coding World"

# 网页的标题
title: "Women In Tech"
# 网站的主标题
name: "Missy IT"
description: "Foodie & IT"

# 其它配置, 可忽略, 无需修改
url: site url
icon: your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus: disqus_shortname # get it on https://disqus.com/admin/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

permalink: /:title/

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
exclude: [ changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock ]

theme: jekyll-theme-dinky
